### PR TITLE
Remove dependency on sklearn.externals.joblib, which has been removed

### PR DESCRIPTION
**Pull request by calvinmccarter-at-tempus**

### CODE REVIEW

**Comment by calvinmccarter-at-tempus** [comment]
@mnarayan -- what do you think about these changes?

**Comment by mnarayan** [comment]
@calvinmccarter-at-tempus This looks good, will merge this week after fixing CI

**Comment by mnarayan** [comment]
Independently verified that pytest no longer as import errors. This also fixes #124 and some of the errors reported in #126.

**Comment by jasonlaska** [comment]
@calvinmccarter-at-tempus thanks for updating these

**Comment by mnarayan** [comment]
@calvinmccarter-at-tempus Thanks for this update.

**Pull request merged**
